### PR TITLE
Returns new instance of dot if return value of get is an array

### PR DESCRIPTION
**Pull request by dimitri-koenig**

### CODE REVIEW

**Comment by adbario** [comment]
Hey, what are the pros and cons about this?

**Comment by dimitri-koenig** [comment]
If I get some data like ```$first = $myArray->get('someKey')```, I can continue with that $first variable in Dot fashion, like ```$second = $first->get('someSubkey')```

**Comment by adbario** [comment]
But you could directly use:
```php
$second = $myArray->get('someKey.someSubkey')
```

**Comment by dimitri-koenig** [comment]
Not in every case. Sometimes I take $first, give it over to some object, which continues using it. And I don't want to create a new dot object every time.

**Comment by adbario** [comment]
You mean that you don't want to create a new dot object manually every time. Your change would create new object automatically.

In your case I would do it like this, as if someone else reads your code, it will be clear where and how this new object is coming from:
```php
$first = new Dot($myArray->get('someKey'));
$second = new Dot($first->get('someSubkey'));
```

**Comment by dimitri-koenig** [comment]
In that case I would have such code all over the place instead of doing it once and then just using it's features, thus this PR.

**Comment by adbario** [comment]
I do get your point and it could be useful in many cases. But if you want to handle the return as a regular array, i.e. for foreach(), you would need to use:
```php
foreach ($array->all() as $row) {}
```
instead of:
```php
foreach ($array as $row) {}
```
So either way, someone has to write more code anyway.

**Comment by adbario** [comment]
Hey I'm back to this issue now and I think it would be solved with a new method which uses internally the original get() method but returns the result as a new Dot instance if result is an array or array accessible:

```php
/**
 * Get an item from the array and if the item is an array or
 * array accessible, return it as a new Dot instance
 *
 * @param  string $key
 * @param  mixed  $default
 * @return mixed
 */
public function getDot($key, $default = null)
{
    $array = $this->get($key, $default);

    return $this->accessible($array) ? new static($array) : $array;
}
```

**Comment by adbario** [comment]
Or another option would be to add an extra boolean parameter to get() method:
```php
/**
 * Get a value from a path or default value if the path doesn't exist
 *
 * @param  string $key       Path
 * @param  mixed  $default   Default value
 * @param  bool   $returnDot Return new Dot instance if result is an array
 * @return mixed
 */
public function get($key, $default = null, $returnDot = false)
{
    // ....
}
```

With this you could use
```php
$second = $myArray->get('someKey.someSubkey', 'default value or null', true);
```

**Comment by dimitri-koenig** [comment]
Hi Adbar

Thx for your help. After working with this lib for quite some time I must admit that it does not suit my usecase so it does not make any sense to proceed any further. Thx anyway! I guess for your usecases it works perfectly.

**Pull request closed without merging**
